version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install

  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn run test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
